apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcc-app
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dcc-app
      tier: backend
  template:
    metadata:
      labels:
        app: dcc-app
        tier: backend
    spec:
      containers:
      - name: dcc-app
        image: parwin/dcc
